# Generated by Django 4.2.16 on 2024-09-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this shuold be treated as active. Unselect this instead of deleting account.', verbose_name='active'),
        ),
    ]
