# Generated by Django 4.2.16 on 2024-09-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0003_rename_address_l_profile_address_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contry',
            new_name='country',
        ),
    ]
